use_frameworks!

platform :ios, '9.0'

target 'CammentSDK_Example' do
  pod 'CammentSDK', :path => '../'

  target 'CammentSDK_Tests' do
      
    inherit! :search_paths
    
    pod 'Specta'
    pod 'Expecta'
    pod 'OCMock'
    
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['ENABLE_BITCODE'] = 'NO'
          end
      end
  end
end
